purpose: "Design or inspect a controlled, evidence-only interrogation workbench for authorized targets across macOS/iOS, web/React, and OSS, with strict legal/safety guardrails."
triggers:
  - "When asked to build or update the recon workbench toolchain, schemas, or probe catalogs"
  - "When asked to inspect or run probes on an authorized target and produce evidence-backed outputs"
inputs:
  - name: "target_type"
    type: "string"
    required: false
  - name: "authorization_scope"
    type: "string"
    required: true
  - name: "goal"
    type: "string"
    required: false
outputs:
  - name: "workbench_design"
    type: "markdown"
  - name: "probe_plan"
    type: "markdown"
  - name: "findings_report"
    type: "markdown"
non_goals:
  - "Circumvention, DRM bypass, or unauthorized data access"
  - "Claims without artifact evidence"
risks:
  - "Running probes without clear authorization; mitigate by requiring authorization_scope and citing evidence paths"
