classDiagram
  class storybook_story_c7b57404 {
    +skills-antigravity/ui-ux-creative-coding/assets/storybook-story.tsx
  }
  class radix_wrapper_782f1842 {
    +skills-antigravity/ui-ux-creative-coding/assets/radix-wrapper.tsx
  }
  class screen_slide_template_e71dd5d5 {
    +skills-antigravity/stitch-remotion/resources/screen-slide-template.tsx
  }
  class WalkthroughComposition_06d6b3a9 {
    +skills-antigravity/stitch-remotion/examples/WalkthroughComposition.tsx
  }
  class component_template_955baf83 {
    +skills-antigravity/stitch-react-components/resources/component-template.tsx
  }
  class gold_standard_card_ce9d59eb {
    +skills-antigravity/stitch-react-components/examples/gold-standard-card.tsx
  }
  class form_pattern_8f93bc34 {
    +skills-antigravity/shadcn-ui/examples/form-pattern.tsx
  }
  class data_table_e0dd6841 {
    +skills-antigravity/shadcn-ui/examples/data-table.tsx
  }
  class auth_layout_716db075 {
    +skills-antigravity/shadcn-ui/examples/auth-layout.tsx
  }
  class component_template_1_29868136 {
    +frontend/stitch-react-components/resources/component-template.tsx
  }
  class gold_standard_card_1_02ec10fa {
    +frontend/stitch-react-components/examples/gold-standard-card.tsx
  }
  class text_animations_word_highlight_c209c964 {
    +skills-antigravity/remotion/rules/assets/text-animations-word-highlight.tsx
  }
  class text_animations_typewriter_49c51e3b {
    +skills-antigravity/remotion/rules/assets/text-animations-typewriter.tsx
  }
  class charts_bar_chart_e4aa31b4 {
    +skills-antigravity/remotion/rules/assets/charts-bar-chart.tsx
  }
  class storybook_story_1_9df83cc2 {
    +frontend/ui/ui-ux-creative-coding/assets/storybook-story.tsx
  }
  class radix_wrapper_1_af63dc71 {
    +frontend/ui/ui-ux-creative-coding/assets/radix-wrapper.tsx
  }
  class screen_slide_template_1_d4990aa4 {
    +frontend/ui/stitch-remotion/resources/screen-slide-template.tsx
  }
  class WalkthroughComposition_1_b56ec9a6 {
    +frontend/ui/stitch-remotion/examples/WalkthroughComposition.tsx
  }
  class form_pattern_1_158bcfab {
    +frontend/ui/shadcn-ui/examples/form-pattern.tsx
  }
  class data_table_1_2ea7511b {
    +frontend/ui/shadcn-ui/examples/data-table.tsx
  }