classDiagram
  class retry_agent_d_c2b0b332 {
    +github/automate-github-issues/node_modules/undici-types/retry-agent.d.ts
  }
  class readable_d_44aac15f {
    +github/automate-github-issues/node_modules/undici-types/readable.d.ts
  }
  class proxy_agent_d_dd4ecd18 {
    +github/automate-github-issues/node_modules/undici-types/proxy-agent.d.ts
  }
  class pool_d_29d28dba {
    +github/automate-github-issues/node_modules/undici-types/pool.d.ts
  }
  class mock_pool_d_e7d0fd28 {
    +github/automate-github-issues/node_modules/undici-types/mock-pool.d.ts
  }
  class mock_interceptor_d_7fdd789e {
    +github/automate-github-issues/node_modules/undici-types/mock-interceptor.d.ts
  }
  class mock_errors_d_f154d508 {
    +github/automate-github-issues/node_modules/undici-types/mock-errors.d.ts
  }
  class mock_client_d_27ba0321 {
    +github/automate-github-issues/node_modules/undici-types/mock-client.d.ts
  }
  class mock_agent_d_eab6f9dd {
    +github/automate-github-issues/node_modules/undici-types/mock-agent.d.ts
  }
  class filereader_d_3146daf4 {
    +github/automate-github-issues/node_modules/undici-types/filereader.d.ts
  }
  class file_d_142c246c {
    +github/automate-github-issues/node_modules/undici-types/file.d.ts
  }
  class fetch_d_dd156bed {
    +github/automate-github-issues/node_modules/undici-types/fetch.d.ts
  }
  class errors_d_8c4228da {
    +github/automate-github-issues/node_modules/undici-types/errors.d.ts
  }
  class env_http_proxy_agent_d_0d478388 {
    +github/automate-github-issues/node_modules/undici-types/env-http-proxy-agent.d.ts
  }
  class dispatcher_d_98ad032f {
    +github/automate-github-issues/node_modules/undici-types/dispatcher.d.ts
  }
  class client_d_91d07758 {
    +github/automate-github-issues/node_modules/undici-types/client.d.ts
  }
  class balanced_pool_d_96157505 {
    +github/automate-github-issues/node_modules/undici-types/balanced-pool.d.ts
  }
  class agent_d_4125eae9 {
    +github/automate-github-issues/node_modules/undici-types/agent.d.ts
  }
  class toad_cache_d_5066ab84 {
    +github/automate-github-issues/node_modules/toad-cache/toad-cache.d.ts
  }
  class bottleneck_d_00b7a483 {
    +github/automate-github-issues/node_modules/bottleneck/bottleneck.d.ts
  }