graph LR
  node_fs_df6b52af["node:fs"] --> render_887270d0
  node_path_0e7d56ab["node:path"] --> render_887270d0
  node_child_process_cb73900b["node:child_process"] --> render_887270d0
  node_child_process_cb73900b["node:child_process"] --> render_887270d0
  node_fs_df6b52af["node:fs"] --> create_html_c2843377
  node_path_0e7d56ab["node:path"] --> create_html_c2843377
  _google_jules_sdk_8cc83a26["@google/jules-sdk"] --> fleet_plan_7a1dd79c
  node_path_0e7d56ab["node:path"] --> fleet_merge_0cb86c46
  node_fs_df6b52af["node:fs"] --> fleet_merge_0cb86c46
  find_up_b88e7497["find-up"] --> fleet_merge_0cb86c46
  _google_jules_sdk_8cc83a26["@google/jules-sdk"] --> fleet_merge_0cb86c46
  node_path_0e7d56ab["node:path"] --> fleet_dispatch_1b54456c
  node_fs_df6b52af["node:fs"] --> fleet_dispatch_1b54456c
  find_up_b88e7497["find-up"] --> fleet_dispatch_1b54456c
  _google_jules_sdk_8cc83a26["@google/jules-sdk"] --> fleet_dispatch_1b54456c
  zod_4f63cf5c["zod"] --> api_error_envelope_fc8693a0
  octokit_37e6cc65["octokit"] --> issues_02e3fe5a
  node_fs_df6b52af["node:fs"] --> git_9a881b9b
  node_path_0e7d56ab["node:path"] --> git_9a881b9b
  yocto_queue_9ec04120["yocto-queue"] --> index_d_1_0f747669
  tsd_b4d5d517["tsd"] --> index_test_d_800599b6
  tsd_b4d5d517["tsd"] --> index_test_d_1_e909297c
  unicorn_magic_d4bad747["unicorn-magic"] --> index_d_4_89c8e619
  node_path_0e7d56ab["node:path"] --> index_d_4_89c8e619
  unicorn_magic_d4bad747["unicorn-magic"] --> index_d_4_89c8e619
  stream_dca83e71["stream"] --> readable_d_44aac15f
  buffer_d0ca8c2a["buffer"] --> readable_d_44aac15f
  url_28e5ebab["url"] --> pool_d_29d28dba
  buffer_d0ca8c2a["buffer"] --> filereader_d_3146daf4
  buffer_d0ca8c2a["buffer"] --> file_d_142c246c
  buffer_d0ca8c2a["buffer"] --> fetch_d_dd156bed
  url_28e5ebab["url"] --> fetch_d_dd156bed
  stream_dca83e71["stream"] --> fetch_d_dd156bed
  _fastify_busboy_c641e5c9["@fastify/busboy"] --> fetch_d_dd156bed
  node_stream_63504aac["node:stream"] --> fetch_d_dd156bed
  url_28e5ebab["url"] --> dispatcher_d_98ad032f
  stream_dca83e71["stream"] --> dispatcher_d_98ad032f
  events_862417b9["events"] --> dispatcher_d_98ad032f
  buffer_d0ca8c2a["buffer"] --> dispatcher_d_98ad032f
  net_a08a0fcb["net"] --> diagnostics_channel_d_f4fa59f7
  url_28e5ebab["url"] --> diagnostics_channel_d_f4fa59f7
  tls_b7e651cb["tls"] --> connector_d_1e6540f7
  net_a08a0fcb["net"] --> connector_d_1e6540f7
  url_28e5ebab["url"] --> client_d_91d07758
  tls_b7e651cb["tls"] --> client_d_91d07758
  url_28e5ebab["url"] --> balanced_pool_d_96157505
  url_28e5ebab["url"] --> api_d_aed6c350
  stream_dca83e71["stream"] --> api_d_aed6c350
  url_28e5ebab["url"] --> agent_d_4125eae9
  path_exists_bd72dbab["path-exists"] --> index_d_6_b3a48dcc
  path_exists_bd72dbab["path-exists"] --> index_d_6_b3a48dcc
  path_exists_bd72dbab["path-exists"] --> index_d_8_b4d7aa95
  p_locate_9b98410f["p-locate"] --> index_d_8_b4d7aa95
  locate_path_cae6cdc8["locate-path"] --> index_d_9_48e2613c
  locate_path_cae6cdc8["locate-path"] --> index_d_9_48e2613c
  locate_path_cae6cdc8["locate-path"] --> index_d_10_ddffdcaf
  find_up_b88e7497["find-up"] --> index_d_10_ddffdcaf
  node_path_0e7d56ab["node:path"] --> index_d_10_ddffdcaf
  find_up_b88e7497["find-up"] --> index_d_10_ddffdcaf
  find_up_b88e7497["find-up"] --> index_d_10_ddffdcaf
  node_path_0e7d56ab["node:path"] --> index_d_10_ddffdcaf
  find_up_b88e7497["find-up"] --> index_d_10_ddffdcaf
  find_up_b88e7497["find-up"] --> index_d_10_ddffdcaf
  node_path_0e7d56ab["node:path"] --> index_d_10_ddffdcaf
  find_up_b88e7497["find-up"] --> index_d_10_ddffdcaf
  find_up_b88e7497["find-up"] --> index_d_10_ddffdcaf
  node_path_0e7d56ab["node:path"] --> index_d_10_ddffdcaf
  find_up_b88e7497["find-up"] --> index_d_10_ddffdcaf
  find_up_b88e7497["find-up"] --> index_d_10_ddffdcaf
  find_up_b88e7497["find-up"] --> index_d_10_ddffdcaf
  bottleneck_da24c316["bottleneck"] --> test_9f86d081
  assert_25450689["assert"] --> test_9f86d081
  ioredis_818394aa["ioredis"] --> bottleneck_d_00b7a483
  redis_34fb46c8["redis"] --> bottleneck_d_00b7a483
  ioredis_818394aa["ioredis"] --> bottleneck_d_00b7a483
  mod_e55cffc8["mod"] --> typescript_d_5cd334d6
  mod_e55cffc8["mod"] --> typescript_d_5cd334d6
  mod_e55cffc8["mod"] --> typescript_d_5cd334d6
  mod_e55cffc8["mod"] --> typescript_d_5cd334d6
  mod_e55cffc8["mod"] --> typescript_d_5cd334d6
  mod_e55cffc8["mod"] --> typescript_d_5cd334d6
  mod_e55cffc8["mod"] --> typescript_d_5cd334d6
  mod_e55cffc8["mod"] --> typescript_d_5cd334d6
  mod_e55cffc8["mod"] --> typescript_d_5cd334d6
  fs_dce7cce0["fs"] --> typescript_d_5cd334d6
  mod_e55cffc8["mod"] --> typescript_d_5cd334d6
  mod_e55cffc8["mod"] --> typescript_d_5cd334d6
  mod_e55cffc8["mod"] --> typescript_d_5cd334d6
  mod_e55cffc8["mod"] --> typescript_d_5cd334d6
  style node_fs_df6b52af fill:#f59e0b,color:#fff
  style node_path_0e7d56ab fill:#f59e0b,color:#fff
  style node_child_process_cb73900b fill:#f59e0b,color:#fff
  style _google_jules_sdk_8cc83a26 fill:#f59e0b,color:#fff
  style find_up_b88e7497 fill:#f59e0b,color:#fff
  style zod_4f63cf5c fill:#f59e0b,color:#fff
  style octokit_37e6cc65 fill:#f59e0b,color:#fff
  style yocto_queue_9ec04120 fill:#f59e0b,color:#fff
  style tsd_b4d5d517 fill:#f59e0b,color:#fff
  style unicorn_magic_d4bad747 fill:#f59e0b,color:#fff
  style stream_dca83e71 fill:#f59e0b,color:#fff
  style buffer_d0ca8c2a fill:#f59e0b,color:#fff
  style url_28e5ebab fill:#f59e0b,color:#fff
  style _fastify_busboy_c641e5c9 fill:#f59e0b,color:#fff
  style node_stream_63504aac fill:#f59e0b,color:#fff
  style events_862417b9 fill:#f59e0b,color:#fff
  style net_a08a0fcb fill:#f59e0b,color:#fff
  style tls_b7e651cb fill:#f59e0b,color:#fff
  style path_exists_bd72dbab fill:#f59e0b,color:#fff
  style p_locate_9b98410f fill:#f59e0b,color:#fff
  style locate_path_cae6cdc8 fill:#f59e0b,color:#fff
  style bottleneck_da24c316 fill:#f59e0b,color:#fff
  style assert_25450689 fill:#f59e0b,color:#fff
  style ioredis_818394aa fill:#f59e0b,color:#fff
  style redis_34fb46c8 fill:#f59e0b,color:#fff
  style mod_e55cffc8 fill:#f59e0b,color:#fff
  style fs_dce7cce0 fill:#f59e0b,color:#fff