flowchart TD
  Untrusted["Untrusted input"]
  tool_template_74b2d502["tool-template"]
  Untrusted --> tool_template_74b2d502
  tool_template_1_966768c3["tool-template"]
  Untrusted --> tool_template_1_966768c3
  verify_skill_catalog_freshness_a896cce8["verify_skill_catalog_freshness"]
  Untrusted --> verify_skill_catalog_freshness_a896cce8
  verify_router_schema_10b5c390["verify_router_schema"]
  Untrusted --> verify_router_schema_10b5c390
  verify_recursive_skill_graph_artifacts_62510fc1["verify_recursive_skill_graph_artifacts"]
  Untrusted --> verify_recursive_skill_graph_artifacts_62510fc1
  verify_question_lifecycle_contract_91025cb7["verify_question_lifecycle_contract"]
  Untrusted --> verify_question_lifecycle_contract_91025cb7
  test_verify_recursive_skill_graph_artifacts_d745a5ae["test_verify_recursive_skill_graph_artifacts"]
  Untrusted --> test_verify_recursive_skill_graph_artifacts_d745a5ae
  run_skill_genome_loop_ab174e95["run_skill_genome_loop"]
  Untrusted --> run_skill_genome_loop_ab174e95
  docs_lint_75ec99ae["docs_lint"]
  Untrusted --> docs_lint_75ec99ae
  build_skill_state_map_de83c93f["build_skill_state_map"]
  Untrusted --> build_skill_state_map_de83c93f
  validate_skill_graph_profiles_dac972b4["validate_skill_graph_profiles"]
  Untrusted --> validate_skill_graph_profiles_dac972b4
  validate_recursive_promotion_cb35db6c["validate_recursive_promotion"]
  Untrusted --> validate_recursive_promotion_cb35db6c
  test_skill_router_1b78daf2["test_skill_router"]
  Untrusted --> test_skill_router_1b78daf2
  test_openclaw_skill_guard_211fb499["test_openclaw_skill_guard"]
  Untrusted --> test_openclaw_skill_guard_211fb499
  skill_subject_scoreboard_ea503635["skill_subject_scoreboard"]
  Untrusted --> skill_subject_scoreboard_ea503635
  skill_router_c50379b5["skill_router"]
  Untrusted --> skill_router_c50379b5
  skill_graph_inventory_d67c61e6["skill_graph_inventory"]
  Untrusted --> skill_graph_inventory_d67c61e6
  skill_gate_1b2f3166["skill_gate"]
  Untrusted --> skill_gate_1b2f3166
  run_repo_skill_quality_7f7a10ff["run_repo_skill_quality"]
  Untrusted --> run_repo_skill_quality_7f7a10ff
  router_controls_a32cc79f["router_controls"]
  Untrusted --> router_controls_a32cc79f
  refresh_benchmark_policy_4dda5e84["refresh_benchmark_policy"]
  Untrusted --> refresh_benchmark_policy_4dda5e84
  recursive_skill_loop_aa940a84["recursive_skill_loop"]
  Untrusted --> recursive_skill_loop_aa940a84
  record_skill_feedback_75f2db5a["record_skill_feedback"]
  Untrusted --> record_skill_feedback_75f2db5a
  generate_skill_graph_profiles_d432f2ea["generate_skill_graph_profiles"]
  Untrusted --> generate_skill_graph_profiles_d432f2ea
  benchmark_skill_portfolio_43dd74df["benchmark_skill_portfolio"]
  Untrusted --> benchmark_skill_portfolio_43dd74df
  plugin_builder_e9cff287["plugin_builder"]
  Untrusted --> plugin_builder_e9cff287
  audit_codex_home_9c47a803["audit_codex_home"]
  Untrusted --> audit_codex_home_9c47a803
  sora_a4c745fa["sora"]
  Untrusted --> sora_a4c745fa
  validate_skill_graph_profiles_1_e0892d0f["validate_skill_graph_profiles"]
  Untrusted --> validate_skill_graph_profiles_1_e0892d0f
  validate_recursive_promotion_1_bc45160d["validate_recursive_promotion"]
  Untrusted --> validate_recursive_promotion_1_bc45160d
  test_skill_router_1_9a354ca8["test_skill_router"]
  Untrusted --> test_skill_router_1_9a354ca8
  test_openclaw_skill_guard_1_7c2a13f3["test_openclaw_skill_guard"]
  Untrusted --> test_openclaw_skill_guard_1_7c2a13f3
  skill_subject_scoreboard_1_d0314212["skill_subject_scoreboard"]
  Untrusted --> skill_subject_scoreboard_1_d0314212
  skill_router_1_aeb4bedb["skill_router"]
  Untrusted --> skill_router_1_aeb4bedb
  skill_graph_inventory_1_5039fbfd["skill_graph_inventory"]
  Untrusted --> skill_graph_inventory_1_5039fbfd
  skill_gate_1_94fb6889["skill_gate"]
  Untrusted --> skill_gate_1_94fb6889
  run_repo_skill_quality_1_8b14eef4["run_repo_skill_quality"]
  Untrusted --> run_repo_skill_quality_1_8b14eef4
  router_controls_1_0f3341a5["router_controls"]
  Untrusted --> router_controls_1_0f3341a5
  refresh_benchmark_policy_1_28d48340["refresh_benchmark_policy"]
  Untrusted --> refresh_benchmark_policy_1_28d48340
  recursive_skill_loop_1_c584be9a["recursive_skill_loop"]
  Untrusted --> recursive_skill_loop_1_c584be9a
  record_skill_feedback_1_4f0f4947["record_skill_feedback"]
  Untrusted --> record_skill_feedback_1_4f0f4947
  generate_skill_graph_profiles_1_38d0a308["generate_skill_graph_profiles"]
  Untrusted --> generate_skill_graph_profiles_1_38d0a308
  benchmark_skill_portfolio_1_c5e54948["benchmark_skill_portfolio"]
  Untrusted --> benchmark_skill_portfolio_1_c5e54948
  run_ownership_map_e4120ef7["run_ownership_map"]
  Untrusted --> run_ownership_map_e4120ef7
  query_ownership_61d5e843["query_ownership"]
  Untrusted --> query_ownership_61d5e843
  community_maintainers_498bebd5["community_maintainers"]
  Untrusted --> community_maintainers_498bebd5
  build_ownership_map_53db368d["build_ownership_map"]
  Untrusted --> build_ownership_map_53db368d
  oak_api_fetch_a0b53f3b["oak_api_fetch"]
  Untrusted --> oak_api_fetch_a0b53f3b
  image_gen_ad36dde7["image_gen"]
  Untrusted --> image_gen_ad36dde7
  check_brand_guidelines_ebe0aa6a["check_brand_guidelines"]
  Untrusted --> check_brand_guidelines_ebe0aa6a
  bootstrap_doc_qa_2db0bed6["bootstrap_doc_qa"]
  Untrusted --> bootstrap_doc_qa_2db0bed6
  audit_codex_home_1_b4fc56c4["audit_codex_home"]
  Untrusted --> audit_codex_home_1_b4fc56c4
  run_ownership_map_1_7b0bed20["run_ownership_map"]
  Untrusted --> run_ownership_map_1_7b0bed20
  query_ownership_1_1d217bbb["query_ownership"]
  Untrusted --> query_ownership_1_1d217bbb
  community_maintainers_1_2d95cd80["community_maintainers"]
  Untrusted --> community_maintainers_1_2d95cd80
  build_ownership_map_1_bb939757["build_ownership_map"]
  Untrusted --> build_ownership_map_1_bb939757
  oak_api_fetch_1_41850e0b["oak_api_fetch"]
  Untrusted --> oak_api_fetch_1_41850e0b
  check_brand_guidelines_1_72ab5c73["check_brand_guidelines"]
  Untrusted --> check_brand_guidelines_1_72ab5c73
  bootstrap_doc_qa_1_902ba7fb["bootstrap_doc_qa"]
  Untrusted --> bootstrap_doc_qa_1_902ba7fb
  sora_1_a455af61["sora"]
  Untrusted --> sora_1_a455af61
  image_gen_1_d075472d["image_gen"]
  Untrusted --> image_gen_1_d075472d
  build_graph_index_7aaca8ab["build_graph_index"]
  Untrusted --> build_graph_index_7aaca8ab
  _graph_lib_7ca77d9e["_graph_lib"]
  Untrusted --> _graph_lib_7ca77d9e
  auth_layout_716db075["auth-layout"]
  Untrusted --> auth_layout_716db075
  auth_layout_1_20956e9e["auth-layout"]
  Untrusted --> auth_layout_1_20956e9e
  test_sync_mcp_bc0aa8db["test_sync_mcp"]
  Untrusted --> test_sync_mcp_bc0aa8db
  sync_mcp_63bbc5df["sync_mcp"]
  Untrusted --> sync_mcp_63bbc5df
  openclaw_skill_guard_3dba2e87["openclaw_skill_guard"]
  Untrusted --> openclaw_skill_guard_3dba2e87
  deterministic_trace_checks_74950b39["deterministic_trace_checks"]
  Untrusted --> deterministic_trace_checks_74950b39
  browser_session_1ad989be["browser_session"]
  Untrusted --> browser_session_1ad989be
  auth_manager_d402d795["auth_manager"]
  Untrusted --> auth_manager_d402d795
  scan_codex_sessions_ab2978a6["scan_codex_sessions"]
  Untrusted --> scan_codex_sessions_ab2978a6
  correlate_multi_source_skill_failures_bb8c3a36["correlate_multi_source_skill_failures"]
  Untrusted --> correlate_multi_source_skill_failures_bb8c3a36
  openclaw_skill_guard_1_1a658fd4["openclaw_skill_guard"]
  Untrusted --> openclaw_skill_guard_1_1a658fd4
  deterministic_trace_checks_1_0a4a8ad7["deterministic_trace_checks"]
  Untrusted --> deterministic_trace_checks_1_0a4a8ad7
  browser_session_1_7bce9b11["browser_session"]
  Untrusted --> browser_session_1_7bce9b11
  auth_manager_1_f45ad268["auth_manager"]
  Untrusted --> auth_manager_1_f45ad268
  connections_1e5fac86["connections"]
  Untrusted --> connections_1e5fac86
  scan_codex_sessions_1_518bff22["scan_codex_sessions"]
  Untrusted --> scan_codex_sessions_1_518bff22
  correlate_multi_source_skill_failures_1_5d121587["correlate_multi_source_skill_failures"]
  Untrusted --> correlate_multi_source_skill_failures_1_5d121587
  connections_1_72396b07["connections"]
  Untrusted --> connections_1_72396b07
  setup_environment_cb611b05["setup_environment"]
  Untrusted --> setup_environment_cb611b05
  ask_question_2f5dd588["ask_question"]
  Untrusted --> ask_question_2f5dd588
  inspect_pr_checks_8eb8c9ba["inspect_pr_checks"]
  Untrusted --> inspect_pr_checks_8eb8c9ba
  github_pr_3e9d1c41["github-pr"]
  Untrusted --> github_pr_3e9d1c41
  fetch_comments_63be772c["fetch_comments"]
  Untrusted --> fetch_comments_63be772c
  inspect_pr_checks_1_9560c34e["inspect_pr_checks"]
  Untrusted --> inspect_pr_checks_1_9560c34e
  setup_environment_1_e33b563c["setup_environment"]
  Untrusted --> setup_environment_1_e33b563c
  ask_question_1_e6bb4d54["ask_question"]
  Untrusted --> ask_question_1_e6bb4d54
  inspect_pr_checks_2_fc066b4f["inspect_pr_checks"]
  Untrusted --> inspect_pr_checks_2_fc066b4f
  github_pr_1_18a80186["github-pr"]
  Untrusted --> github_pr_1_18a80186
  check_watch_mode_readiness_b521ad1b["check_watch_mode_readiness"]
  Untrusted --> check_watch_mode_readiness_b521ad1b
  check_watch_mode_readiness_1_11860954["check_watch_mode_readiness"]
  Untrusted --> check_watch_mode_readiness_1_11860954
  classDef securityNode fill:#dc2626,color:#fff
