flowchart LR
  User(("User"))
  fleet_merge_0cb86c46["fleet-merge"]
  User --> fleet_merge_0cb86c46
  api_error_envelope_fc8693a0["api-error-envelope"]
  User --> api_error_envelope_fc8693a0
  index_d_1_0f747669["index.d"]
  User --> index_d_1_0f747669
  retry_handler_d_2d3d60a2["retry-handler.d"]
  User --> retry_handler_d_2d3d60a2
  mock_client_d_27ba0321["mock-client.d"]
  User --> mock_client_d_27ba0321
  handlers_d_acfb32c8["handlers.d"]
  User --> handlers_d_acfb32c8
  formdata_d_49123c71["formdata.d"]
  User --> formdata_d_49123c71
  file_d_142c246c["file.d"]
  User --> file_d_142c246c
  client_d_91d07758["client.d"]
  User --> client_d_91d07758
  api_d_aed6c350["api.d"]
  User --> api_d_aed6c350
  public_api_d_84787cea["public-api.d"]
  User --> public_api_d_84787cea
  options_d_ae5597a4["options.d"]
  User --> options_d_ae5597a4
  typescript_d_5cd334d6["typescript.d"]
  User --> typescript_d_5cd334d6
  lib_webworker_iterable_d_35ac2e57["lib.webworker.iterable.d"]
  User --> lib_webworker_iterable_d_35ac2e57
  classDef userNode fill:#16a34a,color:#fff