graph LR
  _google_jules_sdk_8cc83a26["@google/jules-sdk"] --> fleet_plan_7a1dd79c
  node_path_0e7d56ab["node:path"] --> fleet_merge_0cb86c46
  node_fs_df6b52af["node:fs"] --> fleet_merge_0cb86c46
  find_up_b88e7497["find-up"] --> fleet_merge_0cb86c46
  _google_jules_sdk_8cc83a26["@google/jules-sdk"] --> fleet_merge_0cb86c46
  node_path_0e7d56ab["node:path"] --> fleet_dispatch_1b54456c
  node_fs_df6b52af["node:fs"] --> fleet_dispatch_1b54456c
  find_up_b88e7497["find-up"] --> fleet_dispatch_1b54456c
  _google_jules_sdk_8cc83a26["@google/jules-sdk"] --> fleet_dispatch_1b54456c
  octokit_37e6cc65["octokit"] --> issues_02e3fe5a
  node_fs_df6b52af["node:fs"] --> git_9a881b9b
  node_path_0e7d56ab["node:path"] --> git_9a881b9b
  style _google_jules_sdk_8cc83a26 fill:#f59e0b,color:#fff
  style node_path_0e7d56ab fill:#f59e0b,color:#fff
  style node_fs_df6b52af fill:#f59e0b,color:#fff
  style find_up_b88e7497 fill:#f59e0b,color:#fff
  style octokit_37e6cc65 fill:#f59e0b,color:#fff