flowchart TD
  Start(["Start"])
  types_8d846022["types"]
  Start --> types_8d846022
  fleet_plan_7a1dd79c["fleet-plan"]
  types_8d846022 --> fleet_plan_7a1dd79c
  fleet_merge_0cb86c46["fleet-merge"]
  fleet_plan_7a1dd79c --> fleet_merge_0cb86c46
  fleet_dispatch_1b54456c["fleet-dispatch"]
  fleet_merge_0cb86c46 --> fleet_dispatch_1b54456c
  fleet_analyze_1a7bcc95["fleet-analyze"]
  fleet_dispatch_1b54456c --> fleet_analyze_1a7bcc95
  bootstrap_333c04dd["bootstrap"]
  fleet_analyze_1a7bcc95 --> bootstrap_333c04dd
  analyze_issues_217eec6e["analyze-issues"]
  bootstrap_333c04dd --> analyze_issues_217eec6e
  markdown_bc18f706["markdown"]
  analyze_issues_217eec6e --> markdown_bc18f706
  End(["End"])
  markdown_bc18f706 --> End