purpose: "Provide expert guidance and code fixes for Swift Concurrency with minimal behavior change."
triggers:
  - "When the user asks about Swift concurrency, async/await, actors, or tasks"
  - "When Swift 5.x/6.x concurrency diagnostics or Sendable errors are present"
  - "When migrating code to Swift 6 strict concurrency"
inputs:
  - name: "diagnostics"
    type: "string"
    required: false
  - name: "code_context"
    type: "string"
    required: false
  - name: "project_settings"
    type: "string"
    required: false
outputs:
  - name: "code_changes"
    type: "diff or patch"
  - name: "rationale"
    type: "markdown"
  - name: "verification_steps"
    type: "markdown"
non_goals:
  - "Large-scale rewrites unrelated to concurrency safety"
  - "Behavioral changes without user request"
risks:
  - "Incorrect isolation assumptions can change runtime behavior; mitigate by confirming build settings and minimizing blast radius"
