purpose: "Guide users through drafting, improving, and QAing documentation with a structured, reader-first workflow."
triggers:
  - "When the user asks to write or revise docs (README, spec, proposal, decision doc, runbook, API docs)"
  - "When the user asks for doc review, doc QA, checklists, or templates"
inputs:
  - name: "doc_targets"
    type: "string"
    required: true
  - name: "audience"
    type: "string"
    required: true
  - name: "constraints"
    type: "string"
    required: false
  - name: "existing_content"
    type: "string"
    required: false
outputs:
  - name: "updated_docs"
    type: "markdown"
  - name: "qa_summary"
    type: "markdown"
  - name: "open_questions"
    type: "markdown"
  - name: "evidence_bundle"
    type: "markdown"
non_goals:
  - "Provide legal, compliance, or policy advice beyond documentation best practices"
  - "Invent commands, versions, or behaviors that are not verified"
  - "Expose secrets or internal endpoints"
risks:
  - "Hallucinated steps or commands; mitigate by checking repo sources and flagging unknowns"
  - "Sensitive data exposure; mitigate by using placeholders and least-privilege guidance"
  - "Brand or accessibility non-compliance; mitigate via checklists and explicit validation"
