schema_version: 1
purpose: ""
triggers: []
non_goals: []
risks: []
inputs:
  - name: request
    type: text
outputs:
  - name: response
    type: text
quality:
  redaction: required
validation:
  fail_fast: true
