#!/usr/bin/env python3
"""Command-independent rooted runtime projection safety helpers."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

from runtime_surface_policy import PROJECTION_MIXED, runtime_surface_report
from selection_policy import ROOT_SKILL_SET_NAMES


ROOT_SKILL_SET_NAMES_SET = set(ROOT_SKILL_SET_NAMES)
DIRECT_ROOTED_RUNTIME_VISIBILITIES = {"flat", "root"}


def is_generated_root_skill_dir(path: Path) -> bool:
    """Return whether a first-level runtime directory was generated by rooted projection."""
    skill_md = path / "SKILL.md"
    if not path.is_dir() or path.is_symlink() or not skill_md.is_file():
        return False
    try:
        head = skill_md.read_text(encoding="utf-8", errors="ignore")[:600]
    except OSError:
        return False
    return "skill-type: root-skill-set" in head and "projection-mode: rooted" in head


def prune_generated_root_skill_dirs(target_dir: Path, keep_names: set[str], dry_run: bool = False) -> list[str]:
    """Remove generated root-skill directories under target_dir that are no longer owned."""
    logs: list[str] = []
    if not target_dir.exists():
        return logs
    for item in sorted(target_dir.iterdir()):
        if item.name.startswith(".") or item.name in keep_names:
            continue
        if not is_generated_root_skill_dir(item):
            continue
        logs.append(f"Removed generated root skill set: {item}")
        if not dry_run:
            shutil.rmtree(item)
    return logs


def prune_unowned_skillset_files(skillsets_dir: Path, dry_run: bool = False) -> list[str]:
    """Prune files in .skillsets that are not approved rooted manifest files."""
    logs: list[str] = []
    if not skillsets_dir.exists():
        return logs

    allowed = {
        Path(skill_set) / "manifest.jsonl"
        for skill_set in ROOT_SKILL_SET_NAMES_SET
    }
    allowed.add(Path("command-surface.json"))
    for item in sorted(skillsets_dir.rglob("*"), key=lambda path: path.as_posix(), reverse=True):
        if item.is_dir() and not item.is_symlink():
            continue
        try:
            rel_path = item.relative_to(skillsets_dir)
        except ValueError:
            continue
        if rel_path in allowed:
            continue
        logs.append(f"Removed unowned skill-set file: {item}")
        if not dry_run:
            item.unlink()
    return logs


def _direct_runtime_rows_from_manifest_report(manifest_report: dict[str, object]) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    manifests = manifest_report.get("manifests") if isinstance(manifest_report, dict) else None
    if not isinstance(manifests, list):
        return rows
    for manifest in manifests:
        if not isinstance(manifest, dict):
            continue
        manifest_rows = manifest.get("rows")
        if not isinstance(manifest_rows, list):
            continue
        for row in manifest_rows:
            if not isinstance(row, dict):
                continue
            runtime_visibility = str(row.get("runtime_visibility") or "latent").strip().lower()
            source_path = str(row.get("source_path") or "").strip()
            handle = str(row.get("id") or row.get("handle") or "").strip()
            if (
                runtime_visibility in DIRECT_ROOTED_RUNTIME_VISIBILITIES
                and handle
                and source_path.startswith("Skills/")
            ):
                rows.append({
                    "handle": handle,
                    "source_path": source_path,
                    "runtime_visibility": runtime_visibility,
                })
    return sorted(rows, key=lambda row: (row["handle"], row["source_path"]))


def direct_runtime_rows_from_skillsets(skillsets_dir: Path) -> list[dict[str, str]]:
    """Return first-party direct runtime rows from generated rooted manifests."""
    rows: list[dict[str, str]] = []
    if not skillsets_dir.is_dir():
        return rows
    for manifest_path in sorted(skillsets_dir.glob("*/manifest.jsonl")):
        try:
            lines = manifest_path.read_text(encoding="utf-8").splitlines()
        except OSError:
            continue
        manifest_rows: list[dict[str, object]] = []
        for line in lines:
            if not line.strip():
                continue
            try:
                payload = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(payload, dict):
                manifest_rows.append(payload)
        rows.extend(_direct_runtime_rows_from_manifest_report({"manifests": [{"rows": manifest_rows}]}))
    deduped = {(row["handle"], row["source_path"]): row for row in rows}
    return sorted(deduped.values(), key=lambda row: (row["handle"], row["source_path"]))


def direct_runtime_rows_from_manifest_report(manifest_report: dict[str, object]) -> list[dict[str, str]]:
    """Return first-party direct runtime rows from an in-memory manifest report."""
    deduped = {
        (row["handle"], row["source_path"]): row
        for row in _direct_runtime_rows_from_manifest_report(manifest_report)
    }
    return sorted(deduped.values(), key=lambda row: (row["handle"], row["source_path"]))


def direct_runtime_names_from_manifest_report(manifest_report: dict[str, object]) -> set[str]:
    """Return first-level runtime names required by direct rooted handles."""
    return {row["handle"] for row in direct_runtime_rows_from_manifest_report(manifest_report)}


def direct_runtime_names_from_skillsets(skillsets_dir: Path) -> set[str]:
    """Return first-level runtime names required by current rooted manifests."""
    return {row["handle"] for row in direct_runtime_rows_from_skillsets(skillsets_dir)}


def validate_workspace_runtime(
    skills_dir: Path,
    *,
    repo_root_path: Path | None = None,
    direct_runtime_names: set[str] | None = None,
) -> list[dict[str, object]]:
    """Return rooted-projection runtime violations for a workspace .agents/skills directory."""
    if not skills_dir.is_dir():
        return [{
            "code": "ROOTED_WORKSPACE_RUNTIME_MISSING",
            "message": f"Workspace runtime directory is missing: {skills_dir}",
        }]

    root = repo_root_path or skills_dir.parents[2]
    expected_direct_names = (
        set(direct_runtime_names)
        if direct_runtime_names is not None
        else direct_runtime_names_from_skillsets(root / ".skillsets")
    )
    expected_names = ROOT_SKILL_SET_NAMES_SET | expected_direct_names
    first_level = sorted(
        item.name
        for item in skills_dir.iterdir()
        if not item.name.startswith(".") and item.is_dir() and (item / "SKILL.md").is_file()
    )
    surface = runtime_surface_report(first_level)
    violations: list[dict[str, object]] = []
    actual_names = set(first_level)

    unexpected = sorted(actual_names - expected_names)
    missing = sorted(expected_names - actual_names)
    if unexpected or missing:
        violations.append({
            "code": "ROOTED_WORKSPACE_POLICY_NAME_DRIFT",
            "message": "workspace first-level runtime entries differ from rooted policy and declared direct handles",
            "missing": missing,
            "extra": unexpected,
            "expected_direct_names": sorted(expected_direct_names),
        })

    non_generated_roots = sorted(
        root_name
        for root_name in ROOT_SKILL_SET_NAMES_SET & surface.first_level_names
        if not is_generated_root_skill_dir(skills_dir / root_name)
    )
    if non_generated_roots:
        violations.append({
            "code": "ROOTED_WORKSPACE_ROOTS_NOT_GENERATED",
            "message": "workspace rooted entries were not generated by rooted projection",
            "roots": non_generated_roots,
        })
    return violations


def build_user_relink_plan(skills_dir: Path, *, home: Path | None = None) -> list[dict[str, str]]:
    """Return user runtime symlink relink operations for a rooted workspace runtime."""
    home_dir = home or Path.home()
    return [
        {"from": str(home_dir / ".agents" / "skills"), "to": str(skills_dir)},
        {"from": str(home_dir / ".codex" / "skills"), "to": str(skills_dir)},
    ]
