#!/usr/bin/env python3
"""Command-independent rooted runtime projection safety helpers."""

from __future__ import annotations

import shutil
from pathlib import Path

from runtime_surface_policy import PROJECTION_MIXED, runtime_surface_report
from selection_policy import ROOT_SKILL_SET_NAMES


ROOT_SKILL_SET_NAMES_SET = set(ROOT_SKILL_SET_NAMES)


def is_generated_root_skill_dir(path: Path) -> bool:
    """Return whether a first-level runtime directory was generated by rooted projection."""
    skill_md = path / "SKILL.md"
    if not path.is_dir() or path.is_symlink() or not skill_md.is_file():
        return False
    try:
        head = skill_md.read_text(encoding="utf-8", errors="ignore")[:600]
    except OSError:
        return False
    return "skill-type: root-skill-set" in head and "projection-mode: rooted" in head


def prune_generated_root_skill_dirs(target_dir: Path, keep_names: set[str], dry_run: bool = False) -> list[str]:
    """Remove generated root-skill directories under target_dir that are no longer owned."""
    logs: list[str] = []
    if not target_dir.exists():
        return logs
    for item in sorted(target_dir.iterdir()):
        if item.name.startswith(".") or item.name in keep_names:
            continue
        if not is_generated_root_skill_dir(item):
            continue
        logs.append(f"Removed generated root skill set: {item}")
        if not dry_run:
            shutil.rmtree(item)
    return logs


def prune_unowned_skillset_files(skillsets_dir: Path, dry_run: bool = False) -> list[str]:
    """Prune files in .skillsets that are not approved rooted manifest files."""
    logs: list[str] = []
    if not skillsets_dir.exists():
        return logs

    allowed = {
        Path(skill_set) / "manifest.jsonl"
        for skill_set in ROOT_SKILL_SET_NAMES_SET
    }
    for item in sorted(skillsets_dir.rglob("*"), key=lambda path: path.as_posix(), reverse=True):
        if item.is_dir() and not item.is_symlink():
            continue
        try:
            rel_path = item.relative_to(skillsets_dir)
        except ValueError:
            continue
        if rel_path in allowed:
            continue
        logs.append(f"Removed unowned skill-set file: {item}")
        if not dry_run:
            item.unlink()
    return logs


def validate_workspace_runtime(skills_dir: Path) -> list[dict[str, object]]:
    """Return rooted-projection runtime violations for a workspace .agents/skills directory."""
    if not skills_dir.is_dir():
        return [{
            "code": "ROOTED_WORKSPACE_RUNTIME_MISSING",
            "message": f"Workspace runtime directory is missing: {skills_dir}",
        }]

    first_level = sorted(
        item.name
        for item in skills_dir.iterdir()
        if not item.name.startswith(".") and item.is_dir() and (item / "SKILL.md").is_file()
    )
    surface = runtime_surface_report(first_level)
    violations: list[dict[str, object]] = []

    if surface.projection_mode == PROJECTION_MIXED:
        violations.append({
            "code": "ROOTED_WORKSPACE_MIXED_PROJECTION",
            "message": "workspace first-level runtime entries mix rooted roots with non-root entries",
            "missing": surface.missing_first_level_names,
            "extra": surface.extra_first_level_names,
        })
    elif surface.missing_first_level_names or surface.extra_first_level_names:
        violations.append({
            "code": "ROOTED_WORKSPACE_POLICY_NAME_DRIFT",
            "message": "workspace first-level runtime entries differ from rooted policy",
            "missing": surface.missing_first_level_names,
            "extra": surface.extra_first_level_names,
        })

    non_generated_roots = sorted(
        root_name
        for root_name in ROOT_SKILL_SET_NAMES_SET & surface.first_level_names
        if not is_generated_root_skill_dir(skills_dir / root_name)
    )
    if non_generated_roots:
        violations.append({
            "code": "ROOTED_WORKSPACE_ROOTS_NOT_GENERATED",
            "message": "workspace rooted entries were not generated by rooted projection",
            "roots": non_generated_roots,
        })
    return violations


def build_user_relink_plan(skills_dir: Path, *, home: Path | None = None) -> list[dict[str, str]]:
    """Return user runtime symlink relink operations for a rooted workspace runtime."""
    home_dir = home or Path.home()
    return [
        {"from": str(home_dir / ".agents" / "skills"), "to": str(skills_dir)},
        {"from": str(home_dir / ".codex" / "skills"), "to": str(skills_dir)},
    ]
