#!/usr/bin/env python3
"""
graph-diff.py  —  Compare two skill-edges JSON snapshots and print a summary.

Used by the PR graph-diff GitHub Actions workflow to post edge deltas as a
PR comment.

Usage:
  python3 Infrastructure/scripts/skill-graph/graph-diff.py <base_edges.json> <head_edges.json>

Output:
  Markdown summary (stdout) — pipe to gh pr comment --body-file -
"""
import json, sys, pathlib

if len(sys.argv) < 3:
    print("Usage: graph-diff.py <base.json> <head.json>", file=sys.stderr)
    sys.exit(1)

base_path = pathlib.Path(sys.argv[1])
head_path = pathlib.Path(sys.argv[2])

def load(p: pathlib.Path) -> dict:
    if not p.exists():
        return {"nodes": [], "edges": []}
    return json.loads(p.read_text())

base = load(base_path)
head = load(head_path)

base_nodes = {n["id"] for n in base.get("nodes", [])}
head_nodes = {n["id"] for n in head.get("nodes", [])}
base_edges = {(e["from"], e["to"]) for e in base.get("edges", [])}
head_edges = {(e["from"], e["to"]) for e in head.get("edges", [])}

added_skills   = sorted(head_nodes - base_nodes)
removed_skills = sorted(base_nodes - head_nodes)
added_edges    = sorted(head_edges - base_edges)
removed_edges  = sorted(base_edges - head_edges)

base_sinks = {n for n in base_nodes if not any(e[1] == n for e in base_edges)}
head_sinks = {n for n in head_nodes if not any(e[1] == n for e in head_edges)}
fixed_sinks = sorted(base_sinks - head_sinks)
new_sinks   = sorted(head_sinks - base_sinks)

lines = ["## 🕸 Skill Graph Diff", ""]
lines.append(f"| Metric | Before | After | Δ |")
lines.append(f"|---|---|---|---|")
lines.append(f"| Skills | {len(base_nodes)} | {len(head_nodes)} | {len(head_nodes)-len(base_nodes):+} |")
lines.append(f"| Edges | {len(base_edges)} | {len(head_edges)} | {len(head_edges)-len(base_edges):+} |")
lines.append(f"| Sink nodes | {len(base_sinks)} | {len(head_sinks)} | {len(head_sinks)-len(base_sinks):+} |")
lines.append("")

if added_skills:
    lines.append(f"**New skills ({len(added_skills)}):** " + ", ".join(f"`{s}`" for s in added_skills))
if removed_skills:
    lines.append(f"**Removed skills ({len(removed_skills)}):** " + ", ".join(f"`{s}`" for s in removed_skills))
if fixed_sinks:
    lines.append(f"**Sinks fixed ({len(fixed_sinks)}):** " + ", ".join(f"`{s}`" for s in fixed_sinks))
if new_sinks:
    lines.append(f"⚠️ **New sink nodes ({len(new_sinks)}):** " + ", ".join(f"`{s}`" for s in new_sinks) +
                 " — nothing routes to these yet.")

if added_edges:
    sample = added_edges[:8]
    lines.append(f"\n**Added edges ({len(added_edges)}):**")
    for a, b in sample:
        lines.append(f"  - `{a}` → `{b}`")
    if len(added_edges) > 8:
        lines.append(f"  - _…and {len(added_edges)-8} more_")

if removed_edges:
    sample = removed_edges[:5]
    lines.append(f"\n**Removed edges ({len(removed_edges)}):**")
    for a, b in sample:
        lines.append(f"  - `{a}` → `{b}`")

if not (added_skills or removed_skills or added_edges or removed_edges):
    lines.append("_No skill graph changes in this PR._")

lines.append("")
lines.append(f"_Generated by `Infrastructure/scripts/skill-graph/graph-diff.py` · base: `{base_path.name}` · head: `{head_path.name}`_")

print("\n".join(lines))
