"""Compatibility test facade for modularized test cases."""

import ask_skills_package_contract_tests_01 as _ask_skills_package_contract_tests_01
import ask_skills_package_contract_tests_02 as _ask_skills_package_contract_tests_02

TestAskSkillsPackageContract01 = _ask_skills_package_contract_tests_01.TestAskSkillsPackageContract
TestAskSkillsPackageContract02 = _ask_skills_package_contract_tests_02.TestAskSkillsPackageContract
