"""Compatibility test facade for modularized test cases."""

import skills_sdk_scenario_quality_tests_01 as _skills_sdk_scenario_quality_tests_01
import skills_sdk_scenario_quality_tests_02 as _skills_sdk_scenario_quality_tests_02

TestSkillsSdkScenarioQuality01 = _skills_sdk_scenario_quality_tests_01.TestSkillsSdkScenarioQuality
TestSkillsSdkScenarioQuality02 = _skills_sdk_scenario_quality_tests_02.TestSkillsSdkScenarioQuality
