"""Compatibility test facade for modularized test cases."""

import skills_sdk_ab_judge_score_tests_01 as _skills_sdk_ab_judge_score_tests_01
import skills_sdk_ab_judge_score_tests_02 as _skills_sdk_ab_judge_score_tests_02

TestSkillsSdkAbJudgeScore01 = _skills_sdk_ab_judge_score_tests_01.TestSkillsSdkAbJudgeScore
TestSkillsSdkAbJudgeScore02 = _skills_sdk_ab_judge_score_tests_02.TestSkillsSdkAbJudgeScore
