"""Compatibility test facade for modularized test cases."""

import ask_cli_impl_tests_01 as _ask_cli_impl_tests_01
import ask_cli_impl_tests_02 as _ask_cli_impl_tests_02
import ask_cli_impl_tests_03 as _ask_cli_impl_tests_03
import ask_cli_impl_tests_04 as _ask_cli_impl_tests_04
import ask_cli_impl_tests_05 as _ask_cli_impl_tests_05
import ask_cli_impl_tests_06 as _ask_cli_impl_tests_06
import ask_cli_impl_tests_07 as _ask_cli_impl_tests_07

TestAskCLI01 = _ask_cli_impl_tests_01.TestAskCLI
TestAskCLI02 = _ask_cli_impl_tests_02.TestAskCLI
TestAskCLI03 = _ask_cli_impl_tests_03.TestAskCLI
TestAskCLI04 = _ask_cli_impl_tests_04.TestAskCLI
TestAskCLI05 = _ask_cli_impl_tests_05.TestAskCLI
TestAskCLI06 = _ask_cli_impl_tests_06.TestAskCLI
TestAskCLI07 = _ask_cli_impl_tests_07.TestAskCLI
