purpose: >
  Guide creation of complete PRDs or technical specifications from any idea via
  interview-led discovery, templated drafting, adversarial review, and diagrams-as-code,
  producing an implementation-ready document saved to spec-output.md.
schema_version: 1.0
triggers:
  - user requests PRD, product requirements, or software design steps
  - user requests technical spec/architecture document
  - user asks to take an idea from concept to production plan
inputs:
  - document_type: PRD | tech
  - starting_point: existing file path or concept description
  - options: interview_mode flag, focus areas (security|scalability|performance|ux|reliability|cost), opponent models
outputs:
  - finalized spec markdown written to spec-output.md and printed
  - debate summary with rounds/cycles, models, key refinements
non_goals:
  - implementation code
  - committing changes or running production deployments
risks:
  - incomplete inputs leading to assumptions; mitigated via interview mode and explicit assumption listing
  - missed security/accessibility requirements; mitigated by mandatory NFR and critique criteria
  - ambiguity in flows; mitigated by diagrams-as-code and debate rounds
