purpose: "Guide building MCP servers and implementing the mKit Cloudflare Workers boilerplate with safe, schema-driven tools."
triggers:
  - "When the user asks to build or design an MCP server"
  - "When the user asks to implement or extend the mKit MCP boilerplate on Cloudflare Workers"
  - "When the user asks for MCP tool schemas, annotations, or Apps SDK UI integration"
inputs:
  - name: "target_stack"
    type: "string"
    required: false
  - name: "transport"
    type: "string"
    required: false
  - name: "mkit_scope"
    type: "string"
    required: false
outputs:
  - name: "schema_version"
    type: "string"
  - name: "implementation_guidance"
    type: "markdown"
  - name: "verification_steps"
    type: "markdown"
non_goals:
  - "Operate third-party APIs without explicit credentials or user approval"
  - "Add dependencies without asking the user"
risks:
  - "Misconfigured auth or billing could impact access; mitigate by least-privilege defaults and explicit verification steps."
