purpose: "Decide the correct Codex primitive (Skill, Custom Prompt, Agent/automation) for a requested capability."
triggers:
  - "User asks how to implement/package/structure a capability in Codex."
  - "Need to choose between Skill, Custom Prompt, or Agent/automation for reuse/governance."
  - "Requests about implicit triggering or cross-project availability."
inputs:
  - name: "capability_description"
    type: "string"
    required: true
    description: "What the user wants to build, including inputs/outputs and context."
  - name: "constraints"
    type: "string"
    required: false
    description: "Time, autonomy, portability, or governance constraints if provided."
outputs:
  - name: "decision_summary"
    type: "markdown"
    description: "Formatted decision block per SKILL.md Step 4."
non_goals:
  - "Do not generate code, CI configs, or runnable automation."
  - "Do not pick hosting/runtime specifics beyond the primitive choice."
risks:
  - "Misclassification leading to wrong packaging; mitigate by following axes in SKILL.md."
  - "Over-automation without governance; mitigate by explicit autonomy/time notes."
  - "Context leakage; mitigate by preferring Skills for reusable logic and documenting triggers."
