purpose: >
  Define expected behavior and outputs for this skill.
schema_version: 1.0
triggers:
  - user requests the capability described in this skill
inputs:
  - user request details
outputs:
  - primary response or artifact
non_goals:
  - out-of-scope work
risks:
  - missing inputs; mitigated by clarifying questions
