purpose: "Provide React UI patterns and component guidance for building or refactoring screens and components."
triggers:
  - "When the user asks for React UI patterns or component guidance"
  - "When designing layouts, routing, or component composition in React"
inputs:
  - name: "target_components"
    type: "string"
    required: false
  - name: "repo_conventions"
    type: "string"
    required: false
outputs:
  - name: "pattern_guidance"
    type: "markdown"
non_goals:
  - "Implementing full features or changing unrelated code"
risks:
  - "Introducing patterns that conflict with repo conventions"
