purpose: "Guide agents through creating, updating, validating, and packaging skills using the SKILL.md format and best practices."
triggers:
  - "When the user asks to create a new skill or update an existing skill"
  - "When the user asks for skill validation, packaging, or trigger tuning"
inputs:
  - name: "skill_name"
    type: "string"
    required: true
  - name: "examples_or_use_cases"
    type: "list"
    required: true
  - name: "existing_skill_path"
    type: "string"
    required: false
  - name: "target_platforms"
    type: "string"
    required: false
outputs:
  - name: "updated_skill_files"
    type: "files"
  - name: "validation_results"
    type: "markdown"
  - name: "packaging_steps_or_artifact"
    type: "markdown"
  - name: "schema_version"
    type: "string"
non_goals:
  - "Implement non-skill application features or modify unrelated code"
  - "Add new dependencies without explicit user approval"
risks:
  - "Incorrect skill guidance or format errors; mitigate by running validators and asking clarifying questions"
